version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
      # - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
      - MYSQL_DATABASE=trust

  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  #   env_file:
  #     - ./backend/.env
