version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/public/upload:/usr/src/app/public/upload
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=3001

    depends_on:
      - backend
    networks:
      - backend-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
      - MYSQL_DATABASE=trust
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8000:80' 
    environment:
      - PMA_ARBITRARY=1 
      - PMA_PORT=3307
      - PMA_HOST=db
      - PMA_PASSWORD=password
      - PMA_USER=testuser
    networks:
      - backend-network

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
